apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume-pcb-replica
  creationTimestamp: null
spec:
  capacity:
    storage: 200Gi
  glusterfs:
    path: pcb-replica
    endpoints: glusterfs-cluster
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
status: { }
