apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-result-volume-claim
  creationTimestamp: null
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
status: {}
