apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-volume-replica-claim
  creationTimestamp: null
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
status: {}
