 # Fluent Bit ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /tmp/ray/session_latest/logs/job-driver*.log
        Tag *
        Path_Key file_path
        Refresh_Interval 5
    [OUTPUT]
        Name loki
        Match *
        Host 10.233.9.177
        Port 3100
        Labels file_path="fluentbit"
        Label_Keys $file_path
    [OUTPUT]
        Name stdout
        Match *