apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ if .Values.mysql.mysqlRootPassword }}
  mysql-root-password: {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysql.mysqlUserPassword }}
  mysql-password:  {{ .Values.mysql.mysqlUserPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
