{{- if .Values.mysqlexporter.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-exporter
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATA_SOURCE_NAME: "{{ .Values.mysqlexporter.mysqlUserexporter }}:{{ .Values.mysql.mysqlRootPassword }}@{{ if .Values.mysqlexporter.protocol }}{{ .Values.mysqlexporter.protocol }}{{ end }}({{ .Release.Name }}:{{ .Values.service.port }})/{{ if .Values.mysqlexporter.db }}{{ .Values.mysqlexporter.db }}{{ end }}{{ if .Values.mysqlexporter.param }}?{{ .Values.mysqlexporter.param }}{{ end }}"
{{- end }}