apiVersion: v2
appVersion: 0.0.1
description: A Helm chart for Kubernetes
icon: https://github.com/ray-project/ray/raw/master/doc/source/images/ray_header_logo.png
name: kuberay-operator
type: application
version: 0.0.1
