kind: Secret
apiVersion: v1
metadata:
    labels:
        app: '{{ template "pcb-vrs.pcb_vrs.fullname" . }}'
        app.kubernetes.io/instance: '{{ $.Release.Name }}'
        app.kubernetes.io/managed-by: '{{ $.Release.Service }}'
        app.kubernetes.io/name: '{{ template "pcb-vrs.pcb_vrs.fullname" $ }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
        helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version }}'
        heritage: '{{ .Release.Service }}'
        release: '{{ .Release.Name }}'
    name: '{{ template "pcb-vrs.pcb_vrs.fullname" . }}'
data: {}
